Updated the GitHub workflows and/or the README file to the latest versions.

diff --git a/.github/workflows/R-CMD-check.yaml b/.github/workflows/R-CMD-check.yaml
--- a/.github/workflows/R-CMD-check.yaml
+++ b/.github/workflows/R-CMD-check.yaml
@@ -25,6 +25,8 @@
 #
 #   ubsan: compile with -fsanitize=undefined and fail on any errors identified.
 #
+#   debug: compile package with -DDEBUG and -UNDEBUG
+#
 #   covr: run in covr mode may be used with 'full' but probably not with others.
 
 on: [push, pull_request]
@@ -87,9 +89,9 @@ jobs:
           then
             config='{"config":[
             {"os":"windows-latest", "r":"release", "timeout":360, "flags":"binaries"},
-            {"os":"macOS-latest", "r":"release", "timeout":360, "flags":"binaries"},
-            {"os":"ubuntu-20.04", "r":"release", "rspm":"https://packagemanager.rstudio.com/cran/__linux__/focal/latest", "timeout":360, "flags":"full, ubsan"},
-            {"os":"ubuntu-20.04", "r":"devel", "rspm":"https://packagemanager.rstudio.com/cran/__linux__/focal/latest", "timeout":360, "flags":"vignettes"},
+            {"os":"macOS-latest", "r":"release", "timeout":360, "flags":"binaries, ubsan"},
+            {"os":"ubuntu-20.04", "r":"release", "rspm":"https://packagemanager.rstudio.com/cran/__linux__/focal/latest", "timeout":360, "flags":"full, ubsan, debug"},
+            {"os":"ubuntu-20.04", "r":"devel", "rspm":"https://packagemanager.rstudio.com/cran/__linux__/focal/latest", "timeout":360, "flags":"vignettes, remote"},
             {"os":"ubuntu-20.04", "r":"release", "rspm":"https://packagemanager.rstudio.com/cran/__linux__/focal/latest", "timeout":360, "flags":"full, covr"}]}'
           elif [[ "${{ env.FOUND_PUBLIC }}" != '0' ]] # Private with no public analogue: reduced set.
           then
@@ -187,6 +189,7 @@ jobs:
         run: |
           remotes::install_cran("tinytex")
           tinytex:::install_yihui_pkgs()
+          tinytex::tlmgr_install("makeindex")
         shell: Rscript {0}
 
       - name: Build
@@ -212,12 +215,13 @@ jobs:
         if: contains(matrix.config.flags, 'covr') == false
         timeout-minutes: ${{ matrix.config.timeout }}
         env:
-          _R_CHECK_CRAN_INCOMING_REMOTE_: false
+          _R_CHECK_CRAN_INCOMING_REMOTE_: ${{ contains(matrix.config.flags, 'remote') }}
           _R_CHECK_FORCE_SUGGESTS_: false
           ENABLE_statnet_TESTS: ${{ contains(matrix.config.flags, 'full') }}
           R_VIGNETTES: ${{ contains(matrix.config.flags, 'vignettes') }}
           FAIL_ON_WARN: ${{ contains(matrix.config.flags, 'strict') }}
           USE_UBSAN: ${{ contains(matrix.config.flags, 'ubsan') }}
+          SET_DEBUG: ${{ contains(matrix.config.flags, 'debug') }}
         run: |
           if(Sys.getenv("R_VIGNETTES") == "true"){
             check_args <- c("--as-cran")
@@ -227,12 +231,23 @@ jobs:
             build_args <- c("--no-manual", "--no-build-vignettes")
           }
 
+          if(Sys.getenv("ENABLE_statnet_TESTS") == "true"){
+            check_args <- c(check_args, "--run-donttest")
+          }
+
           error_on <- if(Sys.getenv("FAIL_ON_WARN") == "true") "warning" else "error"
 
           if(Sys.getenv("USE_UBSAN") == "true"){
-            Sys.setenv(PKG_LIBS="-fsanitize=undefined",
-                       PKG_CFLAGS="-fsanitize=undefined",
-                       UBSAN_OPTIONS="print_stacktrace=1")
+            Sys.setenv(PKG_LIBS=paste(Sys.getenv("PKG_LIBS"), "-fsanitize=undefined"),
+                       PKG_CFLAGS=paste(Sys.getenv("PKG_CFLAGS"), "-fsanitize=undefined"),
+                       PKG_CXXFLAGS=paste(Sys.getenv("PKG_CXXFLAGS"), "-fsanitize=undefined"),
+                       UBSAN_OPTIONS=paste(Sys.getenv("UBSAN_OPTIONS"), "print_stacktrace=1"))
+          }
+
+          if(Sys.getenv("SET_DEBUG") == "true"){
+            Sys.setenv(PKG_LIBS=paste(Sys.getenv("PKG_LIBS"), "-UNDEBUG -DDEBUG"),
+                       PKG_CXXFLAGS=paste(Sys.getenv("PKG_CXXFLAGS"), "-UNDEBUG -DDEBUG"),
+                       PKG_CFLAGS=paste(Sys.getenv("PKG_CFLAGS"), "-UNDEBUG -DDEBUG"))
           }
 
           rcmdcheck::rcmdcheck(args = check_args, build_args = build_args, error_on = error_on, check_dir = "check")
@@ -240,13 +255,18 @@ jobs:
 
       - name: Check UBSAN output
         if: contains(matrix.config.flags, 'ubsan')
+        # NB: xargs -r only works in GNU, so not on MacOS.
         run: |
-          find check/ -name '*.Rout' -print0 | xargs -r -0 grep -E '\.[hc]:[0-9]+:[0-9]+: +runtime error:' > check/ubsan.err || true
-          if [ -s check/ubsan.err ]
+          find check/ -name '*.Rout' -print0 > check/Rout.list
+          if [ -s check/Rout.list ]
           then
-            echo "UBSAN errors:" >&2
-            cat check/ubsan.err >&2
-            exit 1
+            cat check/Rout.list | xargs -0 grep -E '\.[hc]:[0-9]+:[0-9]+: +runtime error:' > check/ubsan.err || true
+            if [ -s check/ubsan.err ]
+            then
+              echo "UBSAN errors:" >&2
+              cat check/ubsan.err >&2
+              exit 1
+            fi
           fi
         shell: bash
         
@@ -258,6 +278,11 @@ jobs:
           path: |
             check
             !check/*/00_pkg_src
+
+      - name: Preinstall package to work around an issue in covr # can be removed after covr update
+        if: contains(matrix.config.flags, 'covr')
+        run: R CMD INSTALL .
+        shell: bash
 
       - name: Test coverage
         if: contains(matrix.config.flags, 'covr')
